version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn ng build --prod
      - run: yarn ng test --watch=false

      - run:
          command: |
            docker build -t wmjalak.azurecr.io/hello:1.0 .
      - run:
          command: |
          docker login --username $DOCKER_USER --password $DOCKER_PASS wmjalak.azurecr.io
      - run:
          command: |
            docker push wmjalak.azurecr.io/hello:1.0

